version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
